packages:
  - apps/*
  - packages/*
  - apps-e2e/*
  - tooling/*

autoInstallPeers: false
engineStrict: true
preferFrozenLockfile: true
saveExact: true
sharedWorkspaceLockfile: true
strictPeerDependencies: true

minimumReleaseAgeExclude:
  - purejsimage
  - '@cloudflare/vite-plugin@1.52.1'
  - miniflare@5.20260811.1-alpha
  - wrangler@4.123.0

allowBuilds:
  esbuild: true
  workerd: true
